### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by pmmphd** [drivefast/asterisk-res_json#9]
Hi there,

This may no longer be maintained, but here is what I get when I try to compile with asterisk-16.15.1:
```
   [CC] res_json.c -> res_json.o
res_json.c:44:23: error: expected declaration specifiers or ‘...’ before string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: 200656 $")
                       ^~~~~~~~
res_json.c:44:33: error: expected declaration specifiers or ‘...’ before string constant
 ASTERISK_FILE_VERSION(__FILE__, "$Revision: 200656 $")
                                 ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/paul/asterisk-16.15.1/include/asterisk.h:23:0,
                 from res_json.c:42:
res_json.c: In function ‘jsonpretty_exec’:
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: error: ‘Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory’ undeclared (first use in this function)
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: each undeclared identifier is reported only once for each function it appears in
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
res_json.c: In function ‘jsoncompress_exec’:
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: error: ‘Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory’ undeclared (first use in this function)
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
res_json.c: In function ‘jsonelement_exec’:
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: error: ‘Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory’ undeclared (first use in this function)
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
res_json.c: In function ‘jsonvariables_exec’:
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: error: ‘Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory’ undeclared (first use in this function)
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
res_json.c: In function ‘jsonadd_exec’:
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: error: ‘Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory’ undeclared (first use in this function)
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
res_json.c: In function ‘jsonset_exec’:
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: error: ‘Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory’ undeclared (first use in this function)
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
res_json.c: In function ‘jsondelete_exec’:
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: error: ‘Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory’ undeclared (first use in this function)
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^
/home/paul/asterisk-16.15.1/include/asterisk/astmm.h:162:2: note: in definition of macro ‘free’
  Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/paul/asterisk-16.15.1/Makefile.rules:164: recipe for target 'res_json.o' failed
```
Thanks!

**Comment by drivefast** [comment]
Hmmm, that is true, i haven't touched this in a very long while. I think the errors are pretty obvious though, the compiler wants you to use `ast_free()` or `ast_std_free()` instead of `free()`. Try bumping up the revision number to something more contemporary, and maybe make change the function that you call. Pull requests are welcome :)
